export const DRAW_DISTANCE = 2

export const WORLDMAP_SCALE = 1 / 1000

export const SEGMENT_WORLD_SIZE = 8192
export const TILES_PER_SEGMENT = 4
export const WORLD_GRID_COLS = 32
export const WORLD_GRID_ROWS = 24
export const TILE_WORLD_SIZE = SEGMENT_WORLD_SIZE / TILES_PER_SEGMENT
export const WORLD_TILE_COLUMNS = WORLD_GRID_COLS * TILES_PER_SEGMENT
export const WORLD_TILE_ROWS = WORLD_GRID_ROWS * TILES_PER_SEGMENT
export const WORLD_WIDTH_PSX = WORLD_GRID_COLS * SEGMENT_WORLD_SIZE
export const WORLD_DEPTH_PSX = WORLD_GRID_ROWS * SEGMENT_WORLD_SIZE
export const WORLD_WRAP_X = WORLD_WIDTH_PSX * WORLDMAP_SCALE
export const WORLD_WRAP_Z = WORLD_DEPTH_PSX * WORLDMAP_SCALE

export const PSX_ANGLE_UNITS = 4096
export const PSX_ANGLE_TO_RAD = (2 * Math.PI) / PSX_ANGLE_UNITS

export const SEGMENT_SIZE_THREE = SEGMENT_WORLD_SIZE * WORLDMAP_SCALE

export const WALKMESH_USER_DATA_KEY = 'isWalkmesh'

export const TERRAIN_RAY_ORIGIN_Y = 10
export const TERRAIN_RAY_FAR = 20
export const ON_FOOT_ACCESS_BIT = 0x80
export const CANOPY_GROUND_TYPE_MAX = 5
export const CANOPY_PLAYER_DEPTH_PSX = 320
export const ON_FOOT_HEIGHT_TOLERANCE_PSX = 200

export const CHARAONE_MODEL_SCALE = WORLDMAP_SCALE * 256
export const WMSET_MODEL_SCALE = WORLDMAP_SCALE * 100
export const CHARAONE_MODEL_PITCH_X = -Math.PI / 2
export const RAGNAROK_MODEL_HEIGHT_OFFSET = 146 * WORLDMAP_SCALE
