export const WORLDMAP_SCALE = 1 / 1000

export const SEGMENT_WORLD_SIZE = 8192
export const WORLD_GRID_COLS = 32
export const WORLD_GRID_ROWS = 24
export const WORLD_WRAP_X = WORLD_GRID_COLS * SEGMENT_WORLD_SIZE * WORLDMAP_SCALE
export const WORLD_WRAP_Z = WORLD_GRID_ROWS * SEGMENT_WORLD_SIZE * WORLDMAP_SCALE

export const PSX_ANGLE_UNITS = 4096
export const PSX_ANGLE_TO_RAD = (2 * Math.PI) / PSX_ANGLE_UNITS

export const SEGMENT_SIZE_THREE = SEGMENT_WORLD_SIZE * WORLDMAP_SCALE

export const WALKMESH_USER_DATA_KEY = 'isWalkmesh'
