export const VEHICLE_IDS = {
  BALAMB_GARDEN: 48,
  BIKE: 33,
  BOAT_DEFAULT: 64,
  BOAT_FOLLOWING: 66,
  BOAT_INSIDE: 65,
  CAR_CLASS_MAX: 40,
  CAR_CLASS_MIN: 32,
  CAR_SPECIAL: 132,
  CHOCOBO: 49,
  ON_FOOT: 128,
  RAGNAROK: 50,
} as const

export const WORLDMAP_ON_FOOT_CLASS_LIMIT = 10
export const WORLDMAP_TRAIN_MIN = 16
export const WORLDMAP_TRAIN_MAX = 22
