export const WORLDMAP_OPCODES = {
  ADD_ENTITY: -237,
  ADD_ENTITY_ALT: -236,
  ADD_ITEM: -201,
  CHECK_BATTLE_RESULT: -203,
  CHECK_BATTLE_STATE: -223,
  CHECK_BATTLEVAR: -199,
  CHECK_BIT_FLAG: -217,
  CHECK_BUTTON_INPUT: -224,
  CHECK_CHARACTER_DISTANCE: -227,
  CHECK_CHARACTER_LOCATION: -230,
  CHECK_CHARACTER_LOCATION_2: -228,
  CHECK_CHARACTER_LOCATION_EX: -229,
  CHECK_COMBAT_SCENE_ID: -204,
  CHECK_DIALOG_CONFIRMED: -212,
  CHECK_DIALOG_STATE: -215,
  CHECK_ENTITY_PROXIMITY: -233,
  CHECK_LOCATION_DRAW_REGISTER: -222,
  CHECK_LOCATION_FLAG: -206,
  CHECK_MOVEMENT: -200,
  CHECK_RANDOM_NUMBER: -209,
  CHECK_REGION_NUMBER: -250,
  CHECK_TILE_POSITION: -249,
  CHECK_VEHICLE_BOARDED: -231,
  CHECK_VEHICLE_ENTERING: -232,
  CHECK_VEHICLE_TYPE: -247,
  CHECK_WORLD_MAP_STATE: -219,
  CLOSE_TEXT_BOX: -220,
  COMPARE_DIALOG_RESPONSE: -214,
  COMPARE_LOCATION_BYTE: -205,
  COMPARE_SCRIPT_VAR: -211,
  COMPARE_SCRIPT_VAR_GT: -208,
  COMPARE_SCRIPT_VAR_LT: -207,
  ELSE: -245,
  ENDIF: -251,
  EXEC: -252,
  FAIL: -226,
  GOTO: -242,
  GREATER_THAN: -253,
  IF: -255,
  IFBLOCK: -246,
  LTEQ_THAN: -254,
  NESTEDELSE: -243,
  NESTEDIF: -244,
  RETURN: -234,
  RETURN_WITH_CODE_3: -213,
  RETURN_WITH_VALUE: -248,
  SET_BIT_FLAG: -216,
  SET_GLOBAL_EVENT_TRIGGERED: -202,
  SET_RETURN_VALUE: -235,
  SET_SCRIPT_VAR: -210,
  SET_WORLD_MAP_STATE: -218,
  SHOW_CHOICE_BOX: -221,
  SHOW_TEXT_BOX: -225,
  X_GREATER_THAN: -241,
  X_LESS_THAN: -239,
  Y_GREATER_THAN: -240,
  Y_LESS_THAN: -238,
} as const

export type WorldmapOpcode = keyof typeof WORLDMAP_OPCODES

const buildOpcodeNames = (): Partial<Record<number, WorldmapOpcode>> => {
  const result: Partial<Record<number, WorldmapOpcode>> = {}
  for (const [name, id] of Object.entries(WORLDMAP_OPCODES) as [WorldmapOpcode, number][]) {
    result[id] = name
  }
  return result
}

export const OPCODE_NAMES = buildOpcodeNames()
